### ISSUE TITLE
Mime Type 

### ISSUE THREAD

**Issue by snarkturne** [turnermm/news#1]
Hello,
I dont' know if I m writing the right place...
I recently installed news plugin for dokuwiki and noticed that when getting newfeed.php, Chromium Web Browser was printing garbage (whereas Firefox was not). I think Chomium does not guess the content type of the file. I just added  the header line in newsfeed.php :
$filetime = 0;
$curent_time = time();
$xml_file = DOKU_INC . 'news_feed.xml';
header('Content-type: application/xml');  <= Line added
        if(isset($conf['plugin']['news'])) {...

Then chromium prints a... :) beautiful tree structure instead of garbage. 
Note that the plugin works well. It's just more confortable to see the tree structure when getting the newfeed.php file with Chromium.

May be you could include this line in future releases ?

Have a nice day.

**Comment by turnermm** [comment]
I believe this has been done.  Could you check?  Thanks.

**Comment by snarkturne** [comment]
Hi turnermm, 
I dont use the news plugin anymore.
Have a nice day.
