### ISSUE TITLE
News feed are empty

### ISSUE THREAD

**Issue by Polarwelt** [turnermm/news#14]
Hello,
i have installed the news plugin and configure it.
Then i create a page http://wiki.r-s-b.eu/doku.php?id=linux:ubu1 and take the refresh button.
Now i find the ubuntu_news.xml in my top level directory http://wiki.r-s-b.eu/ubuntu_news.xml.
If i open it in a browser instance, i see the channel information, but nothing else. The page is not shown on the feed.
Did you have any idea how to fix the problem?
Sorry about my bad english and thank you.
Greetings Polarwelt

**Comment by turnermm** [comment]
Have you followed the instructions about how to create news items?

**Comment by Polarwelt** [comment]
Yes, i have tested it three times.
- Install the plugin
- copy the newsfeed.php in the top level directory
- change owner and rights
- add config to the page
- refresh news

Every time i click on the "refresh button"  the pubdate in the xml will be edit, but there is further no content.

**Comment by turnermm** [comment]
What do you mean "add config to the page"?

**Comment by Polarwelt** [comment]
```
~~NEWSFEED:3;;ubuntu~~
<Content>
 ~~NOCACHE~~
 
 ~~NEWS_REFRESH:ubuntu~~
```

**Comment by turnermm** [comment]
I'm not sure why, but the multi system is not working.  you will have to use the single mode.  I don't have time now to check out the error.

**Comment by turnermm** [comment]
And I don't currently have the facilities since my test server is down.

**Comment by Polarwelt** [comment]
Single mode have the same problem. 
It's ok, i thank you for your time

**Comment by turnermm** [comment]
I think this is fixed.
