### ISSUE TITLE
multiple possible vulnerabilities

### ISSUE THREAD

**Issue by splitbrain** [turnermm/news#8]
See http://php-grinder.com/project/view/20300

In scripts/newsfeed.php is an XSS vulnerability. I could pass an attack vector to $_POST['feed_ref'];

I haven't check the other reported problems in detail.

**Comment by turnermm** [comment]
On 12/1/2015 12:58 PM, Andreas Gohr wrote:
> See http://php-grinder.com/project/view/20300
>
> In scripts/newsfeed.php is an XSS vulnerability. I could pass an attack
> vector to $_POST['feed_ref'];
>
> I haven't check the other reported problems in detail.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turnermm/news/issues/8>.
>
Something is wrong with grinder.  It's not correctly downloading urls 
from github.

-- 
Myron Turner
http://mturner.org/
https://github.com/turnermm

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by splitbrain** [comment]
What do you mean? I can see the problems listed by grinder in the sources of your github repo?

**Comment by turnermm** [comment]
On 12/2/2015 9:11 AM, Andreas Gohr wrote:
> What do you mean? I can see the problems listed by grinder in the
> sources of your github repo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turnermm/news/issues/8#issuecomment-161327717>.
>
That's I assume from your original.  But I test on test branches:
https://github.com/turnermm/news/tree/grinder
And the other day I used test branches without any issue.
-- 
Myron Turner
http://mturner.org/
https://github.com/turnermm

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by turnermm** [comment]
for instance:
http://php-grinder.com/project/view/21387

**Comment by splitbrain** [comment]
Ah okay. I'm currently going through all DokuWiki plugins with a github repo that trigger warnings in grinder. I go through the reports and do very rough assessment of if the grinder problems could be real vulnerabilities. If so I open issues. All grinder tests I did happened on master, so if you started to fix things in other branches already, please feel free to close my issues. I might continue opening issues for things you already fixed in other branches, just to keep track. Sorry for that. Again, feel free to close anything you have fixed already.

BTW: grinder wants github repository URLs, not zip files.

**Comment by turnermm** [comment]
I used zip, tar.gz, and github URLs, and all have worked, until this morning. I started with github URLs and then tried the others when that failed.

**Comment by turnermm** [comment]
I keep getting the 'Archive Error' message, no matter what url I use. Could you try:
 https://github.com/violetfish/news
violetfish is a second account I keep for testing things.  Thanks. Myron

**Comment by turnermm** [comment]
The error is with grinder.  See for instance another recent github archive that's gottne the same message: http://php-grinder.com/project/view/21417

**Comment by turnermm** [comment]
news plugin vulnerabilities fixed in newsfeed.php

**Comment by turnermm** [comment]
Looks like php-grinder is fixed for github.

**Comment by turnermm** [comment]
http://php-grinder.com/project/view/21978
